[project]
name = 'Blockchain-Based-Supply-Chain-Finance-Trade-Finance-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.invoice-financing]
path = 'contracts/invoice-financing.clar'
clarity_version = 2
epoch = 2.5

[contracts.letter-of-credit]
path = 'contracts/letter-of-credit.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
